ДЗ 1
SamatOmarbaev/2024-2-VK-EDU-Frontend-S-Omarbaev pull request #2
Opened 2024-09-20 07:40 UTC by SamatOmarbaev

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @RomanBarannickov проверить его.

Что было сделано:

- реализовал три функции convertBytesToHuman
- correctSentence и nonUniqueElements - реализовал тест для функции convertBytesToHuman

2024-09-20 09:32 UTC, RomanBarannickov requested changes

2024-09-20 09:32 UTC, RomanBarannickov commented on convertBytesToHuman.js
> +  if (typeof bytes !== 'number' || bytes < 0) {
а если NaN передать?)
добавь проверку на NaN
плюс не забудь добавить тест на это в тесты

2024-09-20 09:32 UTC, RomanBarannickov commented on convertBytesToHuman.test.js
> +  expect(convertBytesToHuman(null)).toBe(false)
1. таста на undefined не хватает
2. плюс не увидел тест на 0

2024-09-21 05:39 UTC, SamatOmarbaev commented on convertBytesToHuman.js
> +  if (typeof bytes !== 'number' || bytes < 0) {
добавил проверку на NaN

2024-09-21 05:39 UTC, SamatOmarbaev commented on convertBytesToHuman.test.js
> +  expect(convertBytesToHuman(null)).toBe(false)
Добавил тесты на undefined, NaN и 0

2024-09-22 07:00 UTC, RomanBarannickov approved these changes
@martinkomitsky, @HaseProgram, @kgrechin approve

2024-09-22 08:33 UTC, kgrechin approved these changes

2024-09-22 12:54 UTC, HaseProgram approved these changes
12!

2024-09-22 12:54 UTC, merged