ДЗ 2
SamatOmarbaev/2024-2-VK-EDU-Frontend-S-Omarbaev pull request #3
Opened 2024-09-28 07:03 UTC by SamatOmarbaev

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @RomanBarannickov проверить его.

Что было сделано:

- Стилизовал форму отправки сообщений в соответствии с макетом
- Установил иконки material icons
- Сделал так, чтобы по нажатию на кнопку Enter, сообщение сохранялось в localStorage и добавлялось к списку сообщений выше
- Поле ввода очищается после нажатия на кнопку Enter
- При обновлении страницы уже "отправленные" сообщения загружаются из localStorage
- Настроил деплой ваших страничек на GitHub Pages

2024-09-29 16:32 UTC, RomanBarannickov commented
прикрепи к описанию PR ссылку на github pages

2024-09-29 17:01 UTC, RomanBarannickov requested changes
1. по UI ок, только со стороны UI, то что сообщения прижаты к правой стороне выглядят плохо, очень много пустого пространства. Мы читаем с лево на право, и видеть почти пустую страницу, чтоб в конце найти сообщение не очень

2. К сожалению по JS сложилось впечатление, что код очень сильно подсмотрели без особого вникания, что к чему. Пока пропускаю, но настоятельно рекомендую, вникать и адаптировать готовые решения, под свои реалии. Нет ничего плохого в подсмотреть решение, понять и разобраться как это работает- это и есть обучение, плохо, чтоб без понимания сути - это не имет отношения к обучению

2024-09-29 17:01 UTC, RomanBarannickov commented on simple-chat/src/index.css
> +    top: 0;
если сделать семантическую верстку, то вроде бы не понадобиться эта штука

2024-09-29 17:01 UTC, RomanBarannickov commented on simple-chat/src/index.html
> +    <div class="root">
все круто но у нас ванила, по этому давай сделаем обычную структуру семантическую структуру header, main, footer

2024-09-29 17:01 UTC, RomanBarannickov commented on simple-chat/src/index.html
> +        <div class="messages" id="messages"></div>
сообщения - это список
давай использовать семантику
ui и li твои бро

2024-09-29 17:01 UTC, RomanBarannickov commented on simple-chat/src/index.html
> +        <div class="message-form">
1.лучше это вынести в отдельный тег footer на уровень header, main, footer
2. сам же в классе стилей указал, что это форм, может тогда вместо просто дива использовать специальный тег form?

2024-09-29 17:01 UTC, RomanBarannickov commented on simple-chat/src/index.html
> +          <button id="send-button" class="material-icons">send</button>
добавить тип кнопки, что это специальная кнопка отправки формы
https://doka.guide/html/button/

2024-09-29 17:01 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +            sendButton.style.display = 'none'
не надо её скрывать 
выглядит странно

2024-09-29 17:01 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +    });
я уже видел похожую дурацкую логику один в один и пока что пропущу мимо это

![image](https://github.com/user-attachments/assets/ae4ff7f0-cf10-4c48-9a66-323be3d538dd)

2024-09-29 17:01 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +            e.preventDefault();
1. логика один в один что и при клике, давай вынесем в отдельную функцию логику и будем переиспользовать функцию, а не код 
2. e.preventDefault(); лучше делать в начале функции
3. а что тут останавливает e.preventDefault();? я могу понять если бы эта функцию была привязана к инпуту внутри формы, и  e.preventDefault() останавливал дефолтное поведение отправки запроса формы на ручку API, а тут что останавливается?

2024-09-29 17:01 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +        if (messageInput.value) {
лучше делать обратные проверки в таких случаях, так уменьшается вложенность и выше читабельность кода
if (!value) {
retrun;
}

полезная логика без ковычек

2024-09-29 17:01 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +    function displayMessages() {
где то просто функции где то стрелочные
давай все функции на стрелочные

2024-09-29 17:01 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +        const messages = JSON.parse(localStorage.getItem('messages')) || [];
вынеси получение сообщений из стораджа в отдельную функцию

2024-09-29 17:01 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +        });
1. функцию создания элемента лучше вынести так же в отдельную функцию и назвать соответствующим образом
2. алгоритм рабочий, но очень не оптимальный, каждый appendChild в messagesDiv, влечет за собой repaint и reflow. Это очень сильно бьет по оптимизации приложения. Приложение в данном случае простое и это не заметно, но в реальном мире - это было бы очень заметно и если сделать массив я думаю элементов 100 000, то UI залагает. Это можно оптимизировать если сделать все одной вставкой через промежуточную ноду

эти статьи должны помочь 
https://doka.guide/tools/how-the-browser-creates-pages/
https://learn.javascript.ru/modifying-document

2024-09-29 17:02 UTC, RomanBarannickov commented
обрати внимание на хедер, ему что то поплохело при большом разрешение
![image](https://github.com/user-attachments/assets/2b2cd592-65c9-4776-8e0c-49f62afc56ad)

2024-09-30 07:05 UTC, SamatOmarbaev commented on simple-chat/src/index.html
> +    <div class="root">
исправил

2024-09-30 07:08 UTC, SamatOmarbaev commented on simple-chat/src/index.html
> +        <div class="messages" id="messages"></div>
исправил, забыл про них изначально)

2024-09-30 07:12 UTC, SamatOmarbaev commented on simple-chat/src/index.html
> +        <div class="message-form">
исправил

2024-09-30 07:13 UTC, SamatOmarbaev commented on simple-chat/src/index.js
> +            sendButton.style.display = 'none'
исправил

2024-09-30 07:16 UTC, SamatOmarbaev commented on simple-chat/src/index.js
> +    });
удалил эту логику, просто написал ее для того чтобы скрывать и показывать кнопку при вводе в инпуте, в макете было так просто

2024-09-30 07:25 UTC, SamatOmarbaev commented on simple-chat/src/index.html
> +          <button id="send-button" class="material-icons">send</button>
добавил тип

2024-09-30 07:31 UTC, SamatOmarbaev commented on simple-chat/src/index.js
> +        const messages = JSON.parse(localStorage.getItem('messages')) || [];
вынес отдельную функцию

2024-09-30 07:38 UTC, SamatOmarbaev commented on simple-chat/src/index.js
> +        if (messageInput.value) {
исправил

2024-09-30 07:45 UTC, SamatOmarbaev commented on simple-chat/src/index.js
> +    function displayMessages() {
исправил

2024-09-30 08:10 UTC, SamatOmarbaev commented on simple-chat/src/index.js
> +            e.preventDefault();
вынес в отдельную функцию и исправил логику

2024-09-30 11:54 UTC, SamatOmarbaev commented on simple-chat/src/index.js
> +        });
исправил

2024-09-30 11:55 UTC, SamatOmarbaev commented on simple-chat/src/index.css
> +    top: 0;
могу убрать, но тогда header не будет зафиксирован сверху

2024-10-01 05:29 UTC, SamatOmarbaev commented on simple-chat/src/index.js
> +            e.preventDefault();
вынес  в отдельную функцию

2024-10-01 06:50 UTC, SamatOmarbaev commented
По поводу того что сообщения прижаты к правой стороне выглядят плохо. Это потому что показаны пока что сообщения только которые я отправляю, если добавить сообщения которые отправляет собеседник, то они слева будут как в макете

2024-10-05 05:53 UTC, RomanBarannickov approved these changes
@martinkomitsky, @HaseProgram, @kgrechin
 апрув

2024-10-05 05:53 UTC, RomanBarannickov commented on simple-chat/src/index.js
> +}
не обязательно к исправлению
все круто, только у тебя функция имеет побочные эффекты. Она сохраняет и в localstorage и в массив добавляет
по хорошему функции должны стремиться иметь по меньше сайд эффектов, если есть возможность писать без них, надо писать без них

тут есть 2 проблемы в этом месте
1. неочевидность где что произошло
2. сейчас два логики связаны и при изменение одной логики, будет так же изменена вторая. Если брать по [SOLID](https://habr.com/ru/companies/ruvds/articles/426413/) то тут нарушены первых два принципа.

решается это все просто, разделением добавление в массив и добавления в сторадж на разные функции
и потом их соединить в одной функции с говорящим названием

2024-10-07 15:26 UTC, SamatOmarbaev commented
> @martinkomitsky, @HaseProgram, @kgrechin сделайте апрув плиз

2024-10-07 19:49 UTC, merged

2024-10-07 19:49 UTC, martinkomitsky commented
12!