dz3
SamatOmarbaev/2024-2-VK-EDU-Frontend-S-Omarbaev pull request #4
Opened 2024-10-10 07:27 UTC by SamatOmarbaev

# Домашнее задание № 3

Прошу @martinkomitsky, @haseprogram, @kgrechin или @RomanBarannickov проверить его.

Что было сделано:

- декомпозировал макет на маленькие части:
1) Шапка (с кнопкой поиска, заголовком, кнопкой "бургер")
2) Чат (с аватаром, заголовком, последним сообщением, временем и индикатором прочитанности/доставленности)
3) "Парящая" кнопка "создать чат"
- заверстал страницу, максимально разбив свой код компонентов (js/css) на разные файлы
- предусмотрел переходы с экрана списка чатов на экран сообщений, который был реализован в предыдущем ДЗ

2024-10-13 18:46 UTC, RomanBarannickov requested changes
1. какая та проблема с путями на стенде, картинки не подгружаются
2. если слишком упороться но едет верстка сообщения на 150px ширине. Добавь min-width
3.безостановочный пульскнопки "добавить чат" выглядит странно
4. структура хранения в локалсторадж не оптимальна. Каждое сообщение отдельно записывается в локал сторадже отдельным полем. Так то локал сторадж не бесконечен. Подумай над тем, что у тебя есть 3 сущности: Чат, Сообщения в этом чате и люди  и как с помощью айди их можно связать. Тебе по факту надо всего 2-3 поля в локал сторадже, а не 100500 на каждое сообщение

2024-10-13 18:46 UTC, RomanBarannickov commented on simple-chat/.gitignore
погугли шаблон чтоб не переписывать файл при каждом чихе

2024-10-13 18:46 UTC, RomanBarannickov commented on simple-chat/src/components/chatList/chatList.js
пишем на стрелочных функциях, а не на обычных. Обычные функции как var, либо их только в классах и объектах

2024-10-13 18:46 UTC, RomanBarannickov commented on simple-chat/src/components/chatList/chatList.js
> +    let people = loadPeople();
если переменная не меняется во времени, предпочтительнее использовать const, а не let

2024-10-13 18:46 UTC, RomanBarannickov commented on simple-chat/src/components/chatWindow/chatWindow.js
> +    }
лучше сделать обратную проверку 
if (!person) 
тогда будет меньше скобок. Меньше скобок выше читабельность

2024-10-13 18:46 UTC, RomanBarannickov commented on simple-chat/src/components/chatWindow/chatWindow.js
> +    }, 5000);
штука прикольная но работает как то странно. Заходя в чат с сообщениями, снова пишет привет как дела, выглядит странно

2024-10-13 18:46 UTC, RomanBarannickov commented on simple-chat/src/components/chatWindow/chatWindow.js
> +        }
обратная проверка была бы лучше и читабельнее

2024-10-13 18:46 UTC, RomanBarannickov commented on simple-chat/src/utils/storage.js
> +    }
else не нужно

2024-10-15 05:32 UTC, SamatOmarbaev commented on simple-chat/src/utils/storage.js
> +    }
исправил

2024-10-15 05:53 UTC, SamatOmarbaev commented on simple-chat/src/components/chatWindow/chatWindow.js
> +        }
исправил

2024-10-15 06:01 UTC, SamatOmarbaev commented on simple-chat/src/components/chatWindow/chatWindow.js
> +    }, 5000);
поправил поведение

2024-10-15 06:03 UTC, SamatOmarbaev commented on simple-chat/src/components/chatWindow/chatWindow.js
> +    }
исправил

2024-10-15 06:03 UTC, SamatOmarbaev commented on simple-chat/src/components/chatList/chatList.js
> +    let people = loadPeople();
исправил

2024-10-15 06:05 UTC, SamatOmarbaev commented on simple-chat/src/components/chatList/chatList.js
исправил

2024-10-15 06:07 UTC, SamatOmarbaev commented on simple-chat/.gitignore
понял, погуглю

2024-10-15 07:26 UTC, SamatOmarbaev commented
постарался исправить все недочеты указанные в комментариях

2024-10-18 16:05 UTC, RomanBarannickov approved these changes
@martinkomitsky, @HaseProgram, @kgrechin
 апрув

2024-10-19 12:19 UTC, merged

2024-10-19 12:19 UTC, martinkomitsky commented
12!