dz 4
SamatOmarbaev/2024-2-VK-EDU-Frontend-S-Omarbaev pull request #5
Opened 2024-10-13 07:59 UTC by SamatOmarbaev

# Домашнее задание № 4

Прошу @martinkomitsky, @haseprogram, @kgrechin или @RomanBarannickov проверить его.

Что было сделано:

- Добавил анимацию на страничках:
1) transition для свойств смены цвета/фона/теней/размеров при :hover
2) добавил анимацию pulse для кнопки
3) добавил анимацию для появляющихся новых сообщений
- Установил viewport для мобильных устройств, чтобы ограничить зону видимости приложения шириной экрана и запретить пользовательский зум

2024-10-20 10:09 UTC, RomanBarannickov commented
пожалуйста, прикрепляй к описанию PR ссылочку на свой демо стенд

2024-10-20 10:28 UTC, RomanBarannickov requested changes
1. на странице самого чата, при высоких разрешениях экрана, давай прижимать все сообщения к правому краю, чтоб не бегать от края к краю глазами, а на мобилке сделаем как сейчас, по разным сторонам. По этому поводу можешь глянуть любые базовые статьи по UX и как человек воспринимает информацию в сети
2. Давай  сделаем при заходе в чат сразу фокус на поле ввода
3. куда то подевалась возможность отправлять сообщения с кнопки enter, которую реализовывали в дз2 ещё
4. все кнопки которые можно тыкать сделай курсором pointer, так более явно станет, что элемент кликабельный
5. сделай какую нибудь анимацию на стрелку отправки при наведение курсором на неё
6. сделай какую нибудь обводку или тень при наведение курсором на кнопку "Назад"
7. кнопки поиск и точки так же  добавь анимацию, хотя бы не большой scale, чтоб по симпатичнее было
8. глянул проблему того, что у тебя картинки поломаны или они поломаны у меня лично на демке, но этот сайт откуда тянуться картинки лично для меня заблочен, по этому глянь какую та альтернативу, чтоб оно работало без vpn в России

Обязательный факультатив на будущие задания, делать в этой домашке не надо
1. должна быть возможность добавить новый чат
2. должна работать фильтрация списка чатов

В остальном всё прилично сделано, мне нравится, продолжай в том же духе

P.s Если у тебя вопросы по моим комментариям, в целом вопросы, проблемы или трудности, или сидишь над заданием без результата в течение 3-5 часов, приходи в личку тг\вк, контакты есть в закрепленном сообщение в чате в вк.
P.s.s я не кусаюсь :-)

2024-10-30 09:09 UTC, SamatOmarbaev commented
исправил моменты которые смог, почти все

2024-10-30 10:25 UTC, RomanBarannickov approved these changes
@martinkomitsky, @HaseProgram, @kgrechin
 апрув
 
 @SamatOmarbaev прощу прощения, я перепутал лево и право. На больших разрешениях прижимать к левому краю
 
 загрузи любую стандартную картинку для аватарки сейчас. У меня всё так же продолжает быть сломаным аватар в списке чатов
 
 в остальном всё круто молодец

2024-10-31 06:36 UTC, HaseProgram approved these changes
Класс, 12!

2024-10-31 06:36 UTC, merged