Lesson 5
SamatOmarbaev/2024-2-VK-EDU-Frontend-S-Omarbaev pull request #6
Opened 2024-10-22 09:36 UTC by SamatOmarbaev

# Домашнее задание № 5

Прошу @martinkomitsky, @haseprogram, @kgrechin или @RomanBarannickov проверить его.

Что было сделано:

- Переписал проект на react

2024-10-23 13:05 UTC, RomanBarannickov requested changes
в целом все хорошо, требуются небольшие доработки

P.s жду правок по дз4
P.s.s приходи в личку тг с вопросами

2024-10-23 13:05 UTC, RomanBarannickov commented on simple-chat/src/components/chatWindow/chatWindow.js
> +        if (messageText) {
1. было верно написано
2. это не то что делает функция sendMessage?

2024-10-23 13:05 UTC, RomanBarannickov commented on .github/workflows/gh-pages.yml
> +          publish_dir: ./react-chat/build
1. vite собирает продакшен сборку в папку dist, а не build из за этого нет ничего на демо стенде
https://samatomarbaev.github.io/2024-2-VK-EDU-Frontend-S-Omarbaev/
2. прикрепи ссылку на стенд в описание PR, пожалуйста, чтоб мне не лазить по actions
3. ты можешь либо build -> dist поменять в этом файле, либо в сборщике прописать, что папка куда собирается билд называется build
4. всегда проверяй, что все успешно развернулось на gp физически зайдя на стенд

2024-10-23 13:05 UTC, RomanBarannickov commented on react-chat/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
а шрифты не надо подключить которые были ранее?

2024-10-23 13:05 UTC, RomanBarannickov commented on react-chat/src/App.jsx
> +        <Chat chatId={activeChatId} onBack={() => setActiveChatId(null)} />
on back вынеси в переменную
есть такое правило, всю логику вычислений по возможности нужно выносить из jsx в переменные и использовать уже только переменные внутри jsx. Т.к сам по себе jsx довольно громоздкий и усложнять его всякой логикой не стоит
плюс это в будущем позволяет проще находить и справлять код

2024-10-23 13:05 UTC, RomanBarannickov commented on react-chat/src/components/ChatList/ChatList.jsx
> +  const people = loadPeople();
у тебя при каждом изменение состояния твоего компонента или состояния родительского компонента, будут перезапрашиваться данные эти. Когда localstorage ты не заметишь трудностей, но когда это будут запросы к беку - может начаться трешь

такие вещи надо складывать в стейт в связке через useEffect
https://react.dev/reference/react/useState
https://react.dev/reference/react/useEffect

2024-10-23 13:05 UTC, RomanBarannickov commented on react-chat/src/components/ChatList/ChatList.jsx
> +        </li>
можно так же вынести как отдельный компонент chatListElement

2024-10-23 13:05 UTC, RomanBarannickov commented on react-chat/src/components/ChatWindow/ChatWindow.jsx
> +    const chat = getChatData()[chatId];
не надо так сокращать
лучше явно писать
чем более явно написан код - легче читать, легче поддерживать

2024-10-23 13:05 UTC, RomanBarannickov commented on react-chat/src/components/ChatWindow/ChatWindow.jsx
> +      setMessages(chat.messages);
а тут молодец, использовал как надо связку, про что я выше писал

2024-10-23 13:05 UTC, RomanBarannickov commented on react-chat/src/components/ChatWindow/ChatWindow.jsx
> +    setMessages((prevMessages) => [...prevMessages, message]);
не первый раз повторяется эта логика - вынеси в отдельную функцию добавление нового элемента, чтоб не повторяться

2024-10-23 13:05 UTC, RomanBarannickov commented on react-chat/src/components/ChatWindow/ChatWindow.jsx
> +      </footer>
я бы советовал вынести в отдельный компонент

2024-10-23 13:05 UTC, RomanBarannickov commented on react-chat/src/components/ChatWindow/ChatWindow.jsx
> +            </li>
так же советовал бы вынести в отдельный компонент
плюс все вычисления лучше вынести из jsx как я писал в переменные и использовать по возможности в jsx только переменные

2024-10-23 13:05 UTC, RomanBarannickov commented on react-chat/src/pages/Chat/Chat.jsx
> +      </header>
1. в отдельный компонент
2. попробуй просто сделать импорт картинки и передать в src, сборщик должен сам все верно сделать, чтоб руками не прописывать так пути

2024-10-23 13:05 UTC, RomanBarannickov commented on react-chat/src/pages/Chat/Chat.jsx
> +  const person = loadPeople().find((p) => p.id === chatId);
снова с людьми эта логика
делается через useState + useEffect и потом вычисляется

плюс ещё круче можно сделать, если много где нужны пользователи, можно написать кастомный хук
который будет делать запрос людей по связке useState + useEffect и из себя возвращать уже готовое значение peopls с которыми можно будет работать синхронно как ты написал в этой строчке

2024-10-23 13:05 UTC, RomanBarannickov commented on react-chat/src/pages/Chat/Chat.jsx
> +        <button onClick={onBack}>
лучше добавить type у кнопки

2024-10-23 13:05 UTC, RomanBarannickov commented on react-chat/src/pages/Chats/Chats.jsx
> +      </header>
если хедер имеет общие вещи на всех страницах, попробуй унифицировать это решение как то в общем компоненте

тип компонент хедер в себе будет содержат общий css и надо будет только childrens кинуть в него как сейчас

компонентный подход подразумевает по возможности максимум переиспользования логики и кода

2024-10-23 13:05 UTC, RomanBarannickov commented on react-chat/src/utils/storage.js
> +    const data = JSON.parse(localStorage.getItem(LOCAL_STORAGE_KEY)) || {};
если чаты - это массив данных, лучше возвращать пустой массив данных. Если чат объект, то как нулевое значение возвращать null, так хотя бы можно хоть как то обработать это и понять в каком мы состояние находимся

2024-10-23 13:05 UTC, RomanBarannickov commented on react-chat/src/utils/storage.js
советую тебе уже начать разносить этот файл на разные файлы и вынести его из utils
в utils ты можешь например в этом файле оставить ток обертку на localstorage чтоб в будущем было легче заменить по какой то причине Localstorage на что то другое

а работу с конкретными сущностями надо начать выносить в папку api/{название сущности}
чтоб файл не начал превращаться в помойку из всего что есть в проекте

2024-11-03 06:22 UTC, SamatOmarbaev commented on simple-chat/src/components/chatWindow/chatWindow.js
> +        if (messageText) {
исправлено в 4 дз

2024-11-03 06:26 UTC, SamatOmarbaev commented on react-chat/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
забыл про них изначально, теперь вернул

2024-11-03 06:28 UTC, SamatOmarbaev commented on react-chat/src/App.jsx
> +        <Chat chatId={activeChatId} onBack={() => setActiveChatId(null)} />
исправлено

2024-11-03 06:34 UTC, SamatOmarbaev commented on react-chat/src/components/ChatList/ChatList.jsx
> +  const people = loadPeople();
исправил на useeffect и usestate

2024-11-03 06:42 UTC, SamatOmarbaev commented on react-chat/src/components/ChatList/ChatList.jsx
> +        </li>
вынес

2024-11-03 06:51 UTC, SamatOmarbaev commented on react-chat/src/components/ChatWindow/ChatWindow.jsx
> +      </footer>
вынес

2024-11-03 06:52 UTC, SamatOmarbaev commented on react-chat/src/components/ChatWindow/ChatWindow.jsx
> +    setMessages((prevMessages) => [...prevMessages, message]);
вынес в отдельную функцию

2024-11-03 07:34 UTC, SamatOmarbaev commented on react-chat/src/pages/Chat/Chat.jsx
> +        <button onClick={onBack}>
добавил

2024-11-03 07:57 UTC, SamatOmarbaev commented on react-chat/src/pages/Chats/Chats.jsx
> +      </header>
вынес в общий компонент

2024-11-03 09:04 UTC, SamatOmarbaev commented on react-chat/src/pages/Chat/Chat.jsx
> +  const person = loadPeople().find((p) => p.id === chatId);
исправил,  вынес логику получения в отдельный хук для читаемости

2024-11-03 09:21 UTC, SamatOmarbaev commented
вроде внес все изменения и исправил недочеты

2024-11-03 09:27 UTC, SamatOmarbaev commented on react-chat/src/components/ChatWindow/ChatWindow.jsx
> +    const chat = getChatData()[chatId];
исправил вроде

2024-11-03 09:33 UTC, SamatOmarbaev commented on react-chat/src/components/ChatWindow/ChatWindow.jsx
> +            </li>
вынес

2024-11-03 09:45 UTC, SamatOmarbaev commented on react-chat/src/utils/storage.js
> +    const data = JSON.parse(localStorage.getItem(LOCAL_STORAGE_KEY)) || {};
вроде исправил, но не уверен что правильно

2024-11-03 09:59 UTC, SamatOmarbaev commented on react-chat/src/pages/Chat/Chat.jsx
> +      </header>
исправил, помогло

2024-11-05 07:04 UTC, RomanBarannickov approved these changes
@martinkomitsky, @HaseProgram, @kgrechin 
 апрув
 
 @SamatOmarbaev в целом всё хорошо. Но где то подсмотрел историю с memo без понимания механизма работы и увидел в это святой грааль оптимизации.
 Писал в комментариях и отпишу тут. Оптимизация не бывает бесплатной. Оптимизация - это компромисс. Между у нас все очень плохо и тем, что мы потратим чуть больше ресурсов клиента, но сделаем по лучше чем было.
 Да, покрывая всё и вся memo и тп, можно случайно попасть в нужное узкое место, но это "палить из пушки по воробьям". И даже случайно оптимизированное узкое место не даст такого прироста приложению, т.к куча ресурсов тратиться на оптимизацию того, чего не следует. Мемоизация в реакт - это такая небольшая ловушка, которая привлекает своей простотой. Но на самом деле это очень и очень сложный инструмент, который требует глубокого понимая работы всех составляющих мемоизации, так и устройства типов в самом js. И только в связке со всем этим можно сделать действительно хорошую оптимизацию
 
 По это я настоятельно рекомендую удалить все memo
 И как совет на будущее. Лучше не использовать какой то инструмент, который не сильно понимаешь как работает. Лучше сначала в нем разобраться и потом только использовать. Потому что используя, что то совсем не известное сам без чьей либо помощи. Можно сделать код ещё хуже и даже не понять этого

2024-11-05 07:04 UTC, RomanBarannickov commented on react-chat/src/components/Button/Button.jsx
> +export const Button = memo(({ children, shadow, animation, onButtonClick }) => {
не надо оптимизировать раньше времени
оптимизация - это не бесплатная история и не такая очевидная как кажется. И реально работает, только в узких местах, которые действительно тупят

плюс тут скорее всего у тебя нормально не работает memo, потому что children передается по ссылки и при каждом обновление ссылка на children новая и компонент все равно перерисовывется

2024-11-05 07:04 UTC, RomanBarannickov commented on react-chat/src/components/Button/Button.module.scss
> +}
используем возможности scss по сокращению кода
https://sass-lang.com/documentation/style-rules/parent-selector/

2024-11-05 07:04 UTC, RomanBarannickov commented on react-chat/src/components/ChatList/ChatList.jsx
> +          key={chat.person.id}
всё же лучше использовать именно id чата

2024-11-05 07:04 UTC, RomanBarannickov commented on react-chat/src/components/ChatListElement/ChatListElement.module.scss
> +}
https://sass-lang.com/documentation/style-rules/parent-selector/

2024-11-05 07:04 UTC, RomanBarannickov commented on react-chat/src/components/ChatWindow/ChatWindow.jsx
> +export const ChatWindow = memo(({ chatId }) => {
и повторюсь
оптимизация не бесплатная
это такой же вызов функции, такое же потребление ресурсов и если просто все компоненты закатывать в memo. Вероятность обратного эффекта по ухудшению производительности возрастает
если у тебя компонент рендерился из за чего то там 5 раз, а стал 1 или 2
это не увеличение производительности
чтоб выявить просадки- это либо прям видно что лагает, либо надо смотреть уже по девтулзам реакт и искать уские места 

опять же в данном конкретном случае, chatId вряд ли меняется 100500 раз, чтоб куча ререндеров было. И тут скорее всего memo в хорошем случае ничего не делает, а в плохом жрет ещё больше ресурсов.

2024-11-05 07:04 UTC, RomanBarannickov commented on react-chat/src/components/FormFooter/FormFooter.jsx
> +export const FormFooter = memo(
и здесь тоже мемо не работает
ты передаешь функцию sendMessage, из родителя. Функция - ссылочный тип. Чтоб зафиксировать ссылку, надо использовать useCallback 
и опять я возвращаюсь к мысли. Посмотри сколько надо доп работы вызвать
useCallback, memo, useMemo, потратить на это ресурсы клиента, память и вычислительные мощности. Куча работы и если в данном компоненте, нет лагов и все было четко - это пустая трата ресурсов

2024-11-05 07:38 UTC, SamatOmarbaev commented on react-chat/src/components/Button/Button.jsx
> +export const Button = memo(({ children, shadow, animation, onButtonClick }) => {
убрал

2024-11-05 07:39 UTC, SamatOmarbaev commented on react-chat/src/components/Button/Button.module.scss
> +}
сократил

2024-11-05 07:40 UTC, SamatOmarbaev commented on react-chat/src/components/ChatListElement/ChatListElement.module.scss
> +}
сократил

2024-11-05 07:40 UTC, SamatOmarbaev commented on react-chat/src/components/ChatWindow/ChatWindow.jsx
> +export const ChatWindow = memo(({ chatId }) => {
убрал

2024-11-05 07:41 UTC, SamatOmarbaev commented on react-chat/src/components/FormFooter/FormFooter.jsx
> +export const FormFooter = memo(
убрал

2024-11-05 07:42 UTC, merged

2024-11-05 07:42 UTC, martinkomitsky commented
12!