Lesson 6
SamatOmarbaev/2024-2-VK-EDU-Frontend-S-Omarbaev pull request #7
Opened 2024-10-31 08:18 UTC by SamatOmarbaev

# Домашнее задание № 6

Прошу @martinkomitsky, @haseprogram, @kgrechin или @RomanBarannickov проверить его.

Что было сделано:

- Добавил react-router-dom
- Сверстал страницу профиля

https://samatomarbaev.github.io/2024-2-VK-EDU-Frontend-S-Omarbaev/

2024-11-01 15:12 UTC, RomanBarannickov requested changes
код не плох, только демка не работает снова. Отписал как поправить, должно помочь. Если нет, приходи в личку в тг
плюс у тебя ещё правки по дз 5 были

2024-11-01 15:12 UTC, RomanBarannickov commented on react-chat/src/App.jsx
> +        <Route path="/chat/:chatId/profile" element={<Profile />} />
все пути / и /chat необходимо вынести в словарь и использовать везде значение из словаря
словарь - это просто объект с полем и значением

2. мне кажется требовалось в задание все же сделать профиль непосредственно пользователя. А не профиль чата

2024-11-01 15:12 UTC, RomanBarannickov commented on react-chat/src/components/ChatList/ChatList.module.scss
> +}
по возможности используем возможности scss
https://sass-lang.com/documentation/style-rules/parent-selector/

2024-11-01 15:12 UTC, RomanBarannickov commented on react-chat/vite.config.js
> +  plugins: [react()],
все также не работает сборка
укажи тут base - это твой url твоего gh-page
https://vite.dev/config/shared-options.html#base

2024-11-01 15:12 UTC, RomanBarannickov commented on react-chat/src/utils/storage.js
разбей этот файл на разные файлы
пусть это будет уже в папке api
api
--chats
--messages
--users

и там храни свои методы по доступу и управлению сущностью. Не важно что сейчас твои данные в LS хранятся. Сегодня в ls завтра на беке. Пиши уже сразу методы, которые можно спокойно использовать в UI. А уже реализацию этих методов скрывай внутри. Так легче поддерживать код

2024-11-01 15:12 UTC, RomanBarannickov commented on react-chat/src/components/ChatList/ChatList.jsx
> +  const people = loadPeople();
сейчас это грузится из LS. Но потом это будет загружаться с бекенда. Сразу используй связку useState + UseEffect

2. Такую общую инфу как юзеры советую загружать на уровне файла App.tsx и передавать внутрь компонентов и страниц через контекст провайдер

2024-11-01 15:12 UTC, RomanBarannickov commented on react-chat/src/components/ChatList/ChatList.jsx
> +          to={`/chat/${chat.person.id}`}
в коде не должно быть хардкода путей. Это потом тяжело поддерживать, если вдруг надо поменять путь будет. Используем словари

2024-11-01 15:12 UTC, RomanBarannickov commented on react-chat/src/components/ChatWindow/ChatWindow.jsx
> +            </li>
вынеси в отдельный компонент
все вычисления вынеси в этом компоненты в переменные

2024-11-01 15:12 UTC, RomanBarannickov commented on react-chat/src/components/ChatWindow/ChatWindow.jsx
> +      </footer>
в отдельный компонент лучше вынести
onChange в отдельную функцию выносим из jsx

2024-11-01 15:12 UTC, RomanBarannickov commented on react-chat/src/pages/Chat/Chat.jsx
> +  const person = loadPeople().find((p) => p.id === chatId);
представляем что это реально Апи
с реальным апи работаем по связке useState + useEffect

2024-11-01 15:12 UTC, RomanBarannickov commented on react-chat/src/pages/Chat/Chat.jsx
> +        <Link to={"profile"} className={styles.HeaderAvatar}>
to берем из словаря путей

2024-11-01 15:12 UTC, RomanBarannickov commented on react-chat/src/pages/Profile/Profile.jsx
> +  const person = loadPeople().find((p) => p.id === chatId);
х3 про загрузки
ну и ещё момент что я уже писал
на реальном апи не логично запрашивать 3 раза одну и туже инфу с бека. Это не эффективно
вынеси получение данных на уровень App и прокидывай через контекст значение

2024-11-03 10:53 UTC, SamatOmarbaev commented on react-chat/vite.config.js
> +  plugins: [react()],
исправил в правках к 5 дз, все заработало

2024-11-03 12:28 UTC, SamatOmarbaev commented
переход на профиль пользователя пока решил сделать при нажатии на кнопку меню, потом надо будет определиться точнее через что переходить в профиль

2024-11-05 07:52 UTC, SamatOmarbaev commented
добавил правки из 5 дз сюда

2024-11-05 14:20 UTC, RomanBarannickov approved these changes
@martinkomitsky, @HaseProgram, @kgrechin
 апрув

2024-11-06 10:01 UTC, martinkomitsky commented
12!

2024-11-06 10:01 UTC, merged