dz 7
SamatOmarbaev/2024-2-VK-EDU-Frontend-S-Omarbaev pull request #8
Opened 2024-11-07 09:24 UTC by SamatOmarbaev

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @RomanBarannickov проверить его.

Что было сделано:

- Начал переход на взаимодействие с бэком

https://samatomarbaev.github.io/2024-2-VK-EDU-Frontend-S-Omarbaev/

2024-11-07 09:25 UTC, SamatOmarbaev commented
Не уверен в корректной работе приложения при взаимодействие с сервером, поэтому благодарен многим замечаниям и что нужно исправить

2024-11-09 12:31 UTC, RomanBarannickov requested changes
комментарий по всем апи сераисам
Я повторяюсь, но я уже давал рекомендации.
Надо сделать один инстанс на всех используя возможности axios
https://axios-http.com/docs/instance

заголовки добавляются 2 способами
либо через мутацию инстанса
либо через интерцептор
вот статья тут все есть про это
https://blog.logrocket.com/using-axios-set-request-headers/


Так. Ну дальше страницы логина я не смог продвинуться. Частично код взят просто as is у кого то без какой либо адаптации. Страница самого чата сообщений даже по коду не рабочая. О каком то реализации long pulling или ws и речи нет для страницы сообщений

2024-11-09 12:31 UTC, RomanBarannickov commented on react-chat/src/App.jsx
> +);
1. писать компоненты в одном файле - это не очень хорошая практика. Один компонет - один файл
2. название компонента как то плохо отражает его суть

2024-11-09 12:31 UTC, RomanBarannickov commented on react-chat/src/App.jsx
> +      window.location.reload();
скорее всего из за этого я не могу войти в приложение
когда так жестко идет перезагрузка страницы. Рушиться вся логика работы SPA приложения. Теряется стейт. Я постоянно остаюсь на странице логина. Сам попробуй зайди на демо стенд и потыкай свой код от лица пользователя

2024-11-09 12:31 UTC, RomanBarannickov commented on react-chat/src/App.jsx
> +  const handleLogin = async (credentials) => {
выноси всю логику связанную со страницей логина. На страницу логин. Все что связано со страницей регистрации - выноси на страницу регистрации. Зачем это всё хранить в app компоненте

2024-11-09 12:31 UTC, RomanBarannickov commented on react-chat/src/App.jsx
> +          path={ROUTES.AUTH}
сделай отдельные страницы для логина и для регистрации. Не надо их объединять

2024-11-09 12:31 UTC, RomanBarannickov commented on react-chat/src/apiService/auth/auth.js
> +let accessToken = '';
так мы не храним аксес токен. Он так хранится только в момент жизни js кода. любая перезагрузка и токен теряется. Я писал это в рекомендациях по 7 домашке. Аксес токен и рефреш токен мы храним в локалсторадже

2024-11-09 12:31 UTC, RomanBarannickov commented on react-chat/src/apiService/auth/auth.js
> +// const API_URL = import.meta.env.VITE_API_URL;
все правильно было. Из env переменных берем значение путей
просто чтоб это работало надо завести env файлы и подправить скрипты в package.json. 
https://main.vitejs.dev/guide/env-and-mode.html

2024-11-09 12:31 UTC, RomanBarannickov commented on react-chat/src/utils/people.js
пользователей удаляем и интегрируемся с беком

2024-11-09 12:31 UTC, RomanBarannickov commented on react-chat/src/apiService/auth/auth.js
> +    localStorage.setItem('refreshToken', refresh);
функции апи мы используем только для вызова апи и в каких то случаях для сериализации данных от бека в нужный нам формат. Мы не делаем всяких сайдэффектов с записью токенов и тп

это делается в других функциях. Пишется условный authServie и там пишется функция логин. Которая дернет апишку и уже она положет токен куда надо

Тоже самое и с предподготовокой данных. этим занимаются отдельные сервисы сущности. Апи сервисы занимаются только отправкой и приемом данных. Но не обработкой этих данных

2024-11-09 12:31 UTC, RomanBarannickov commented on react-chat/src/components/AuthGuard/AuthGuard.jsx
> +      navigate("/auth");
навигацию через ROUTES берем

2024-11-09 12:31 UTC, RomanBarannickov commented on react-chat/src/components/AuthGuard/AuthGuard.jsx
> +export const AuthGuard = ({ param }) => {
я это уже видел решение. Взято не подумав вообще)
откуда взялся такой пропс как param?
подумай и исправь

2024-11-09 12:31 UTC, RomanBarannickov commented on react-chat/src/components/AuthGuard/AuthGuard.jsx
> +      const refToken = localStorage.getItem("refreshToken");
а почему проверка идет именно рефреш токена?
сначала надо проверить аксес токен
и не просто проверить. А надо ещё проверить его время жизни. Что он не протух. Я все это описал в рекомендациях

2024-11-09 12:31 UTC, RomanBarannickov commented on react-chat/src/components/AuthGuard/AuthGuard.jsx
> +  const [isLoggedIn, setIsLoggedIn] = useState(false);
лучше использовать более понятные конечные состояния
для загрузки можно использовать набор строк который будет отображать полноценный спектр состояния запроса типа таких
init | loading | error |  success | idle
для состояния логина пользователя тоже можно что то такое написать. Состояния на флагах очень хрупкие, тяжело расширяемые и плохо поддерживаемые

2024-11-09 12:31 UTC, RomanBarannickov commented on react-chat/src/components/ChatList/ChatList.jsx
> +        const chatBox = await getChats(getAuthHeaders());
снова повтор кода. И про это я так же все писал

2024-11-09 12:31 UTC, RomanBarannickov commented on react-chat/src/components/ChatWindow/ChatWindow.jsx
> +    const loadedMessages = getMessages(chatId);
интересная обработка промиса и сразу его в переменную
да сразу в стейт
тупо по каефу
![image](https://github.com/user-attachments/assets/ac37a16a-1d22-4cfb-b249-7360909d426e)

2024-11-16 08:46 UTC, closed without merging